Repository rafaabatistas/98barbershop, pull requests merged in 2021-11, with the labels that each got.

#27 Feature/visual adjustments
  package.json
  src/components/ui/atoms/UserInfo/UserInfo.styles.ts
  src/components/ui/atoms/UserInfo/UserInfo.test.tsx
  src/components/ui/atoms/UserInfo/UserInfo.tsx
  src/components/ui/atoms/UserInfo/__snapshots__/UserInfo.test.tsx.snap
  src/components/ui/molecules/Heading/Heading.stories.tsx
  src/components/ui/molecules/Heading/Heading.test.tsx
  src/components/ui/molecules/Heading/Heading.tsx
  src/components/ui/molecules/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/ui/molecules/Map/Map.styles.ts
  src/components/ui/molecules/Map/Map.tsx
  src/components/ui/molecules/NavList/NavList.tsx
  src/components/ui/molecules/NavList/__snapshots__/NavList.test.tsx.snap
  src/components/ui/molecules/ReviewBox/ReviewBox.styles.ts
  src/components/ui/molecules/ReviewBox/ReviewBox.tsx
  src/components/ui/molecules/ReviewBox/__snapshots__/ReviewBox.test.tsx.snap
  src/components/ui/molecules/ServiceBox/ServiceBox.styles.ts
  src/components/ui/molecules/ServiceBox/__snapshots__/ServiceBox.test.tsx.snap
  src/components/ui/organisms/Banner/Banner.tsx
  src/components/ui/organisms/BannerSlider/mock.ts
  src/components/ui/organisms/Header/__snapshots__/Header.test.tsx.snap
  src/components/ui/organisms/MainServices/__snapshots__/MainServices.test.tsx.snap
  src/components/ui/organisms/MainServices/mock.ts
  src/components/ui/organisms/Review/__snapshots__/Review.test.tsx.snap
  src/components/ui/organisms/Review/mock.ts
  src/components/ui/organisms/SectionContributors/__snapshots__/SectionContributors.test.tsx.snap
  src/components/ui/templates/HomePage/__snapshots__/HomePage.test.tsx.snap
  src/styles/global.ts
  yarn.lock
Labels: enhancement, wontfix

#28 Feature/section contact
  public/assets/img/foto_indisponivel.jpg
  public/assets/svg/icon-about.svg
  public/assets/svg/icon-error.svg
  public/assets/svg/icon-success.svg
  src/components/ui/atoms/InputRadio/InputRadio.stories.tsx
  src/components/ui/atoms/InputRadio/InputRadio.styles.ts
  src/components/ui/atoms/InputRadio/InputRadio.test.tsx
  src/components/ui/atoms/InputRadio/InputRadio.tsx
  src/components/ui/atoms/InputRadio/__snapshots__/InputRadio.test.tsx.snap
  src/components/ui/molecules/InputGroup/InputGroup.stories.tsx
  src/components/ui/molecules/InputGroup/InputGroup.styles.ts
  src/components/ui/molecules/InputGroup/InputGroup.test.tsx
  src/components/ui/molecules/InputGroup/InputGroup.tsx
  src/components/ui/molecules/InputGroup/__snapshots__/InputGroup.test.tsx.snap
  src/components/ui/molecules/InputRadioGroup/InputRadioGroup.stories.tsx
  src/components/ui/molecules/InputRadioGroup/InputRadioGroup.styles.ts
  src/components/ui/molecules/InputRadioGroup/InputRadioGroup.test.tsx
  src/components/ui/molecules/InputRadioGroup/InputRadioGroup.tsx
  src/components/ui/molecules/InputRadioGroup/__snapshots__/InputRadioGroup.test.tsx.snap
  src/components/ui/molecules/ModalForm/ModalForm.stories.tsx
  src/components/ui/molecules/ModalForm/ModalForm.styles.ts
  src/components/ui/molecules/ModalForm/ModalForm.test.tsx
  src/components/ui/molecules/ModalForm/ModalForm.tsx
  src/components/ui/molecules/ModalForm/__snapshots__/ModalForm.test.tsx.snap
  src/components/ui/molecules/NavList/NavList.tsx
  src/components/ui/molecules/SelectGroup/SelectGroup.stories.tsx
  src/components/ui/molecules/SelectGroup/SelectGroup.styles.ts
  src/components/ui/molecules/SelectGroup/SelectGroup.test.tsx
  src/components/ui/molecules/SelectGroup/SelectGroup.tsx
  src/components/ui/molecules/SelectGroup/__snapshots__/SelectGroup.test.tsx.snap
  src/components/ui/molecules/TextAreaGroup/TextAreaGroup.stories.tsx
  src/components/ui/molecules/TextAreaGroup/TextAreaGroup.styles.ts
  src/components/ui/molecules/TextAreaGroup/TextAreaGroup.test.tsx
  src/components/ui/molecules/TextAreaGroup/TextAreaGroup.tsx
  src/components/ui/molecules/TextAreaGroup/__snapshots__/TextAreaGroup.test.tsx.snap
  src/components/ui/organisms/SectionAbout/SectionAbout.tsx
  src/components/ui/organisms/SectionAbout/__snapshots__/SectionAbout.test.tsx.snap
  src/components/ui/organisms/SectionContact/SectionContact.stories.tsx
  src/components/ui/organisms/SectionContact/SectionContact.styles.ts
  src/components/ui/organisms/SectionContact/SectionContact.test.tsx
  src/components/ui/organisms/SectionContact/SectionContact.tsx
  src/components/ui/templates/HomePage/HomePage.tsx
  src/components/ui/templates/HomePage/__snapshots__/HomePage.test.tsx.snap
  src/styles/theme.ts
Labels: component

#30 Feature/readme and license
  LICENSE
  README.md
  public/assets/svg/logo-readme.svg
Labels: documentation

#29 Feature/function submit form
  .storybook/main.js
  jest.config.js
  package.json
  src/components/ui/atoms/UserInfo/UserInfo.stories.tsx
  src/components/ui/atoms/UserInfo/UserInfo.test.tsx
  src/components/ui/atoms/UserInfo/UserInfo.tsx
  src/components/ui/molecules/ReviewBox/ReviewBox.stories.tsx
  src/components/ui/molecules/ReviewBox/ReviewBox.test.tsx
  src/components/ui/molecules/ReviewBox/ReviewBox.tsx
  src/components/ui/molecules/ReviewBox/__snapshots__/ReviewBox.test.tsx.snap
  src/components/ui/organisms/Review/Review.stories.tsx
  src/components/ui/organisms/Review/Review.test.tsx
  src/components/ui/organisms/Review/Review.tsx
  src/components/ui/organisms/Review/__snapshots__/Review.test.tsx.snap
  src/components/ui/organisms/Review/mock.ts
  src/components/ui/organisms/SectionContact/SectionContact.test.tsx
  src/components/ui/organisms/SectionContact/SectionContact.tsx
  src/components/ui/templates/HomePage/HomePage.tsx
  src/components/ui/templates/HomePage/__snapshots__/HomePage.test.tsx.snap
  src/contexts/ReviewContext.tsx
  src/contexts/contextUtils/providers.tsx
  src/graphql/client.ts
  src/graphql/queries.ts
  src/graphql/types/graphql.ts
  src/pages/_app.tsx
  src/pages/api/evaluations.ts
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: component

#34 Feature/Add Google Analytics
  src/components/ui/atoms/Analytics/Analytics.tsx
  src/pages/_document.tsx
Labels: component

#32 Bugfix/improve function formSubmission
  src/components/ui/organisms/SectionContact/SectionContact.tsx
  src/pages/api/evaluations.ts
  yarn.lock
Labels: wontfix
